[project]
name = "piggy-bank"
authors = []
description = ""
telemetry = false

[contracts.bank]
path = "contracts/bank.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
